{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.storeName }}
  target:
    name: sso-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        github-oidc.json: |-
          {"clientid":"{{ .Values.externalSecret.clientId }}","clientsecret":"{{ `{{ .clientSecret }}` }}"}
  data:
    - secretKey: clientSecret
      remoteRef:
        key: {{ .Values.externalSecret.resourceId }}
        property: password
{{- end }}
{{- if .Values.notationTrust.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notation-trust-store
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.notationTrust.storeName }}
  target:
    name: notation-trust-store
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        jon-soh-re-ca.crt: '{{ `{{ index (fromJson .bundle) "NOTATION_CA_CERTIFICATE" }}` }}'
  data:
    - secretKey: bundle
      remoteRef:
        key: {{ .Values.notationTrust.resourceId }}
        property: password
{{- end }}
