{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.storeName }}
  target:
    name: sso-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: {{ .Values.externalSecret.resourceId }}
        property: password
{{- end }}
