{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.storeName }}
  target:
    name: sso-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        github-oidc.json: |-
          {"clientid":"{{ .Values.externalSecret.clientId }}","clientsecret":"{{ `{{ .clientSecret }}` }}"}
  data:
    - secretKey: clientSecret
      remoteRef:
        key: {{ .Values.externalSecret.resourceId }}
        property: password
{{- end }}
{{- if .Values.cosignPublicKey.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosign-public-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.cosignPublicKey.storeName }}
  target:
    name: cosign-public-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        jon-soh-re.pub: '{{ `{{ index (fromJson .bundle) "COSIGN_PUBLIC_KEY" }}` }}'
  data:
    - secretKey: bundle
      remoteRef:
        key: {{ .Values.cosignPublicKey.resourceId }}
        property: password
{{- end }}
