apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sso-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: sso-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Release.Namespace }}-sso-secret
