apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: zot-virtualservice
spec:
  gateways:
  - istio-system/http-gateway
  hosts:
  - zot.soh.re
  http:
  - route:
    - destination:
        host: zot
        port:
          number: 5000
