apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-tls
  namespace: istio-system
spec:
  dnsNames:
  - jaeger.soh.re
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http
  secretName: jaeger-tls
