apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default "passbolt-secret" .Values.passbolt.passboltEnv.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: {{ default "passbolt-secret" .Values.passbolt.passboltEnv.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        # Vault key name. Defaults to the single 'passbolt' key in the cluster secret store
        key: "passbolt"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
