{{- if .Values.pushSecret.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-pushsecret" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  updatePolicy: Replace
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - name: oracle-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ .Values.pushSecret.selectorSecretName | quote }}
  data:
    - conversionStrategy: None
      match:
        secretKey: dbname
        remoteRef:
          remoteKey: "{{ .Release.Name }}-postgres-app"
          property: DATASOURCES_DEFAULT_DATABASE
    - conversionStrategy: None
      match:
        secretKey: username
        remoteRef:
          remoteKey: "{{ .Release.Name }}-postgres-app"
          property: DATASOURCES_DEFAULT_USERNAME
    - conversionStrategy: None
      match:
        secretKey: password
        remoteRef:
          remoteKey: "{{ .Release.Name }}-postgres-app"
          property: DATASOURCES_DEFAULT_PASSWORD

{{- end }}
