apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name | default .Chart.Name }}-virtualservice
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
{{- range .Values.virtualService.hosts }}
  - {{ . | quote }}
{{- end }}
  gateways:
    - "istio-system/{{ .Release.Namespace }}-gateway"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}
            port:
              number: 80
