{{- range .Values.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  refreshInterval: {{ default "1h" .refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.store.name }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
    {{- if .type }}
    template:
      engineVersion: v2
      type: {{ .type }}
      data:
        {{- if .sources }}
        {{- range .sources }}
        {{- $sourceKey := default "bundle" .secretKey }}
        {{- range .keys }}
        {{ . | quote }}: {{ printf "{{ index (fromJson .%s) %q }}" $sourceKey . | quote }}
        {{- end }}
        {{- end }}
        {{- else }}
        {{- range .keys }}
        {{ . | quote }}: {{ printf "{{ index (fromJson .bundle) %q }}" . | quote }}
        {{- end }}
        {{- end }}
    {{- else if or .keys .sources }}
    template:
      engineVersion: v2
      data:
        {{- if .sources }}
        {{- range .sources }}
        {{- $sourceKey := default "bundle" .secretKey }}
        {{- range .keys }}
        {{ . | quote }}: {{ printf "{{ index (fromJson .%s) %q }}" $sourceKey . | quote }}
        {{- end }}
        {{- end }}
        {{- else }}
        {{- range .keys }}
        {{ . | quote }}: {{ printf "{{ index (fromJson .bundle) %q }}" . | quote }}
        {{- end }}
        {{- end }}
    {{- end }}
  data:
    {{- if .sources }}
    {{- range .sources }}
    - secretKey: {{ default "bundle" .secretKey }}
      remoteRef:
        key: {{ .resourceId }}
        property: {{ default "password" .property }}
    {{- end }}
    {{- else }}
    - secretKey: {{ default "bundle" .secretKey }}
      remoteRef:
        key: {{ .resourceId }}
        property: {{ default "password" .property }}
    {{- end }}
{{- end }}
