apiVersion: scalewatch.soh.re/v1alpha1
kind: RunnerScaleSet
metadata:
  name: runnerscaleset-{{ index .Values "gha-runner-scale-set" "runnerScaleSetName" }}
spec:
  githubConfigSecret: {{ index .Values "gha-runner-scale-set" "githubConfigSecret" | quote }}
  githubConfigURL: {{ index .Values "gha-runner-scale-set" "githubConfigUrl" | quote }}
  name: {{ index .Values "gha-runner-scale-set" "runnerScaleSetName" | quote }}
