apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: harbor
spec:
  gateways:
  - istio-system/http-gateway
  - mesh
  hosts:
    - harbor.soh.re
  http:
    - name: 'registry'
      match:
        - port: 5000
      route:
        - destination:
            host: harbor-registry
            port:
              number: 5000   
    - name: 'core'
      match:
        - uri:
            prefix: '/api/'
        - uri:
            prefix: '/service/'
        - uri:
            prefix: '/v2/'
        - uri:
            prefix: '/chartrepo/'
        - uri:
            prefix: '/c/'
      route:
        - destination:
            host: harbor-core
            port:
              number: 80
    - name: 'portal'
      route:
        - destination:
            host: harbor-portal
            port:
              number: 80
