apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-router
spec:
  selector:
    kubevirt.io/domain: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
