apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: soh-re-tls
  namespace: istio-system
spec:
  dnsNames:
  - soh.re
  - www.soh.re
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http
  secretName: soh-re-tls
