apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: soh-re-virtualservice
spec:
  hosts:
  - "soh.re"
  - "www.soh.re"
  gateways:
  - istio-system/soh-re-gateway
  http:
  - match:
      - headers:
          upgrade:
            exact: "websocket"
    route:
    - destination:
        host: sohk8s-proxy.sohk8s-system.svc.cluster.local
        port:
          number: 9090

  - match:
    - authority:
        regex: ^www\.(.*)
      uri:
        prefix: /
    redirect:
      authority: soh.re

  - match:
    - scheme:
        exact: http
      uri:
        prefix: /
    redirect:
      redirectCode: 302
      scheme: https

  - route:
      - destination:
          host: {{ .Values.name }}
          port:
            number: 80
