apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: soh-websocket-weather-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: soh-websocket
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        # geocoding-api.open-meteo.com
        cidr: 202.61.206.6/32
    - ipBlock:
        # api.open-meteo.com
        cidr: 188.40.99.226/32
    ports:
    - port: 443
      protocol: TCP
