apiVersion: v1
kind: Service
metadata:
  name: {{ include "hockey.fullname" . }}-redis
  labels:
    app: {{ include "hockey.name" . }}
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: {{ include "hockey.name" . }}
    component: redis
