# Use existing Secret which stores DELEGATE_TOKEN key instead of creating a new one. The value should be set with the `DELEGATE_TOKEN` key inside the secret.
## The use of external secrets allows you to manage credentials from external tools like Vault, 1Password, SealedSecrets, among other.
## If set, this parameter takes precedence over "delegateToken".
## Recommendations:
## - Use different Secrets names for `existingUpgraderToken` and `existingDelegateToken`.
## - Do not use Secrets managed by other helm delpoyments.
harness-delegate-ng:
  existingDelegateToken: "delegate-token"
  accountId: "pceuDjVIQT-rztB20qkFZw"
  delegateName: "mainguys-k3s-cluster"
