apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    # Use the Let's Encrypt production environment
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jon@soh.re
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - http01:
        ingress:
          class: istio
