gha-runner-scale-set:
  runnerScaleSetName: self-hosted
  controllerServiceAccount:
    name: github-runners-gha-rs-controller
    namespace: arc-system
  githubConfigUrl: https://github.com/Standouthost
  githubConfigSecret: gha-runner-token
  maxRunners: 10
  minRunners: 1
  runnerGroup: "default"
  template:
    containerMode:
      type: kubernetes

gha-runner-scale-set-controller:
  image:
    repository: "ghcr.io/actions/gha-runner-scale-set-controller"
    pullPolicy: IfNotPresent
    tag: "0.9.3"
  imagePullSecrets: []
  flags:
    excludeLabelPropagationPrefixes:
      - "argocd.argoproj.io/instance"
