{{- if .Values.cert.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Namespace }}-tls
  namespace: istio-system
spec:
  secretName: {{ .Release.Namespace }}-tls
  issuerRef:
    name: {{ .Values.cert.issuer }}
    kind: ClusterIssuer
  dnsNames:
{{- range .Values.virtualService.hosts }}
    - {{ . }}
{{- end }}
{{- end }}
