apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flights-soh-re-tls
  namespace: istio-system
spec:
  dnsNames:
  - flights.soh.re
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http
  secretName: flights-soh-re-tls
