apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: flights-re-virtualservice
spec:
  hosts:
  - "flights.soh.re"
  gateways:
  - istio-system/flights-soh-re-gateway
  http:
  - match:
    - scheme:
        exact: http
      uri:
        prefix: /
    redirect:
      redirectCode: 302
      scheme: https
  - route:
      - destination:
          host: flights.soh.re
          port:
            number: 8080
