{{- $root := . -}}
{{- $org := $root.Values.clusterSecretStore.provider.github.organization -}}
{{- $safeOrg := include "github-secrets.sanitize" $org }}

{{- if and $root.Values.repos (gt (len $root.Values.repos) 0) -}}
  {{- range $i, $repo := $root.Values.repos -}}
    {{- $safeRepo := include "github-secrets.sanitize" $repo }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ printf "github-%s-%s" $safeOrg $safeRepo | trunc 63 | quote }}
spec:
  provider:
    github:
      appID: {{ $root.Values.clusterSecretStore.provider.github.appID }}
      auth:
        privateKey:
          name: {{ $root.Values.clusterSecretStore.provider.github.auth.privateKey.name | quote }}
          key: {{ $root.Values.clusterSecretStore.provider.github.auth.privateKey.key | quote }}
          namespace: {{ $root.Release.Namespace | quote }}
      installationID: {{ $root.Values.clusterSecretStore.provider.github.installationID }}
      organization: {{ $org | quote }}
      repository: {{ $repo | quote }}
---
    {{- end -}}
{{- else -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ printf "github-%s" $safeOrg | trunc 63 | quote }}
spec:
  provider:
    github:
      appID: {{ $root.Values.clusterSecretStore.provider.github.appID }}
      auth:
        privateKey:
          name: {{ $root.Values.clusterSecretStore.provider.github.auth.privateKey.name | quote }}
          key: {{ $root.Values.clusterSecretStore.provider.github.auth.privateKey.key | quote }}
          namespace: {{ $root.Release.Namespace | quote }}
      installationID: {{ $root.Values.clusterSecretStore.provider.github.installationID }}
      organization: {{ $org | quote }}
      # repository omitted when repos list is empty
---
{{- end -}}
