{{- $root := . -}}
{{- $org := $root.Values.clusterSecretStore.provider.github.organization -}}
{{- $safeOrg := include "github-secrets.sanitize" $org }}

{{- if and $root.Values.repos (gt (len $root.Values.repos) 0) -}}
  {{- range $i, $repo := $root.Values.repos -}}
    {{- $safeRepo := include "github-secrets.sanitize" $repo }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "github-docker-secrets-%s-%s" $safeOrg $safeRepo | trunc 63 | quote }}
spec:
  deletionPolicy: {{ $root.Values.pushSecret.deletionPolicy | quote }}
  refreshInterval: {{ $root.Values.pushSecret.refreshInterval | quote }}
  secretStoreRefs:
    - name: {{ printf "github-%s-%s" $safeOrg $safeRepo | trunc 63 | quote }}
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ $root.Values.pushSecret.selectorSecretName | quote }}
  data:
{{- range $i, $d := $root.Values.pushSecret.data }}
    - match:
        secretKey: {{ $d.secretKey | quote }}
        remoteRef:
          remoteKey: {{ $d.remoteKey | quote }}
{{- end }}
---
  {{- end -}}
{{- else -}}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "github-docker-secrets-%s" $safeOrg | trunc 63 | quote }}
spec:
  deletionPolicy: {{ $root.Values.pushSecret.deletionPolicy | quote }}
  refreshInterval: {{ $root.Values.pushSecret.refreshInterval | quote }}
  secretStoreRefs:
    - name: {{ printf "github-%s" $safeOrg | trunc 63 | quote }}
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ $root.Values.pushSecret.selectorSecretName | quote }}
  data:
{{- range $i, $d := $root.Values.pushSecret.data }}
    - match:
        secretKey: {{ $d.secretKey | quote }}
        remoteRef:
          remoteKey: {{ $d.remoteKey | quote }}
{{- end }}
---
{{- end -}}
