zot:
  env: []
  image:
    tag: v2.1.20
  startupProbe:
    failureThreshold: 180
  strategy:
    type: Recreate
    rollingUpdate: null
  service:
    type: ClusterIP
  persistence: true
  pvc:
    create: true
    storage: 80Gi
  nodeSelector:
    kubernetes.io/arch: amd64
  externalSecrets:
    - secretName: "sso-secret"
      mountPath: "/secrets/oidc"
  mountConfig: true
  configFiles:
    config.json: |-
      {
        "storage": {
          "rootDirectory": "/var/lib/registry",
          "fastRestart": true
        },
        "log": { "level": "info" },
        "extensions": {
          "metrics": { "enable": true },
          "search": {
            "enable": true,
            "cve": { "updateInterval": "2h" }
          },
          "ui": { "enable": true }
        },
        "http": {
          "address": "0.0.0.0",
          "port": "5000",
          "externalUrl": "https://zot.soh.re",
          "auth": {
            "openid": {
              "providers": {
                "github": {
                  "credentialsFile": "/secrets/oidc/github-oidc.json",
                  "scopes": ["read:org", "user", "repo"]
                }
              }
            }
          },
          "accessControl": {
            "repositories": {
              "**": {
                "policies": [{
                  "users": ["jon@soh.re"],
                  "actions": ["read", "create", "update", "delete"]
                }],
                "defaultPolicy": ["read"],
                "anonymousPolicy": ["read"]
              }
            }
          }
        }
      }

virtualService:
  hosts:
    - "zot.soh.re"
service:
  name: zot
  targetPort: 5000
name: zot-virtualservice

externalSecret:
  enabled: true
  storeName: passbolt
  resourceId: a604544c-67bd-4080-ae39-27cbca345708
  clientId: Ov23liLygAflIzrCKJhi

sharedPvc:
  enabled: false
  name: zot-rwx
  storage: 80Gi
  storageClassName: longhorn
