zot:
  replicaCount: 2
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: zot-s3-credentials
          key: ZOT_SOH_RE_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: zot-s3-credentials
          key: ZOT_SOH_RE_SECRET_ACCESS_KEY
  image:
    tag: v2.1.20
  startupProbe:
    failureThreshold: 180
  strategy:
    type: RollingUpdate
  service:
    type: ClusterIP
  persistence: true
  pvc:
    create: true
    name: zot-cache
    storage: 1Gi
    storageClassName: longhorn
  serviceHeadless:
    enabled: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - '{{ .Release.Name }}'
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - zot
          topologyKey: kubernetes.io/hostname
  nodeSelector:
    kubernetes.io/arch: amd64
  externalSecrets:
    - secretName: "sso-secret"
      mountPath: "/secrets/oidc"
  mountConfig: true
  configFiles:
    config.json: |-
      {
        "storage": {
          "rootDirectory": "/var/lib/registry",
          "dedupe": false,
          "remoteCache": true,
          "storageDriver": {
            "name": "s3",
            "rootdirectory": "/zot",
            "region": "garage",
            "regionendpoint": "garage.garage.svc.cluster.local:3900",
            "bucket": "zot-soh-re",
            "forcepathstyle": true,
            "secure": false,
            "skipverify": false
          },
          "cacheDriver": {
            "name": "redis",
            "url": "redis://valkey.garage.svc.cluster.local:6379",
            "keyprefix": "zot-soh-re"
          }
        },
        "log": { "level": "info" },
        "extensions": {
          "metrics": { "enable": true },
          "search": {
            "enable": true
          },
          "ui": { "enable": true }
        },
        "http": {
          "address": "0.0.0.0",
          "port": "5000",
          "externalUrl": "https://zot.soh.re",
          "auth": {
            "openid": {
              "providers": {
                "github": {
                  "credentialsFile": "/secrets/oidc/github-oidc.json",
                  "scopes": ["read:org", "user", "repo"]
                }
              }
            }
          },
          "accessControl": {
            "repositories": {
              "**": {
                "policies": [{
                  "users": ["jon@soh.re"],
                  "actions": ["read", "create", "update", "delete"]
                }],
                "defaultPolicy": ["read"],
                "anonymousPolicy": ["read"]
              }
            }
          }
        },
        "cluster": {
          "members": [
            "zot-ha-0.zot-ha-headless.zot.svc.cluster.local:5000",
            "zot-ha-1.zot-ha-headless.zot.svc.cluster.local:5000"
          ],
          "hashKey": "zotsohrecluster1"
        }
      }

cve:
  enabled: true
  image:
    repository: ghcr.io/project-zot/zot
    tag: v2.1.20
    pullPolicy: IfNotPresent
  storage:
    storage: 20Gi
    storageClassName: longhorn
  nodeSelector:
    kubernetes.io/arch: amd64
  configFiles:
    config.json: |-
      {
        "storage": {
          "rootDirectory": "/var/lib/registry",
          "gc": true,
          "gcDelay": "1h",
          "gcInterval": "24h"
        },
        "log": { "level": "info" },
        "extensions": {
          "metrics": { "enable": true },
          "search": {
            "enable": true,
            "cve": { "updateInterval": "2h" }
          },
          "sync": {
            "enable": true,
            "registries": [{
              "urls": ["http://zot-ha:5000"],
              "onDemand": false,
              "pollInterval": "15m",
              "tlsVerify": false,
              "maxRetries": 5,
              "retryDelay": "1m",
              "preserveDigest": true,
              "content": [{ "prefix": "**" }]
            }]
          }
        },
        "http": {
          "address": "0.0.0.0",
          "port": "5000",
          "compat": ["docker2s2"],
          "accessControl": {
            "repositories": {
              "**": {
                "anonymousPolicy": ["read"]
              }
            }
          }
        }
      }

virtualService:
  hosts:
    - "zot.soh.re"
service:
  name: zot-ha
  targetPort: 5000
cveService:
  enabled: true
  name: zot-cve-v2

ha:
  enabled: true
  name: zot-local
  image:
    repository: ghcr.io/project-zot/zot
    tag: v2.1.20
    pullPolicy: IfNotPresent
  storage:
    storageClassName: longhorn-single-replica
    size: 20Gi
  externalSecrets:
    - secretName: sso-secret
      mountPath: /secrets/oidc
  primary:
    nodeName: white-intel
    configFiles:
      config.json: &mainHaConfig |-
        {
          "storage": {
            "rootDirectory": "/var/lib/registry",
            "gc": true,
            "gcDelay": "1h",
            "gcInterval": "24h"
          },
          "log": { "level": "info" },
          "extensions": {
            "metrics": { "enable": true },
            "search": { "enable": true, "cve": { "updateInterval": "2h" } },
            "ui": { "enable": true },
            "sync": {
              "enable": true,
              "registries": [{
                "urls": ["http://zot-ha:5000"],
                "onDemand": false,
                "pollInterval": "5m",
                "tlsVerify": false,
                "maxRetries": 5,
                "retryDelay": "1m",
                "preserveDigest": true,
                "content": [{ "prefix": "**" }]
              }]
            }
          },
          "http": {
            "address": "0.0.0.0",
            "port": "5000",
            "compat": ["docker2s2"],
            "externalUrl": "https://zot.soh.re",
            "auth": {
              "openid": {
                "providers": {
                  "github": {
                    "credentialsFile": "/secrets/oidc/github-oidc.json",
                    "scopes": ["read:org", "user", "repo"]
                  }
                }
              }
            },
            "accessControl": {
              "repositories": {
                "**": {
                  "policies": [{
                    "users": ["jon@soh.re"],
                    "actions": ["read", "create", "update", "delete"]
                  }],
                  "defaultPolicy": ["read"],
                  "anonymousPolicy": ["read"]
                }
              }
            }
          }
        }
  standby:
    nodeName: black-intel
    configFiles:
      config.json: |-
        {
          "storage": {
            "rootDirectory": "/var/lib/registry",
            "gc": true,
            "gcDelay": "1h",
            "gcInterval": "24h"
          },
          "log": { "level": "info" },
          "extensions": {
            "metrics": { "enable": true },
            "search": { "enable": true, "cve": { "updateInterval": "2h" } },
            "ui": { "enable": true },
            "sync": {
              "enable": true,
              "registries": [{
                "urls": ["http://zot-local-primary:5000"],
                "onDemand": false,
                "pollInterval": "5m",
                "tlsVerify": false,
                "maxRetries": 5,
                "retryDelay": "1m",
                "preserveDigest": true,
                "content": [{ "prefix": "**" }]
              }]
            }
          },
          "http": {
            "address": "0.0.0.0",
            "port": "5000",
            "compat": ["docker2s2"],
            "externalUrl": "https://zot.soh.re",
            "auth": {
              "openid": {
                "providers": {
                  "github": {
                    "credentialsFile": "/secrets/oidc/github-oidc.json",
                    "scopes": ["read:org", "user", "repo"]
                  }
                }
              }
            },
            "accessControl": {
              "repositories": {
                "**": {
                  "policies": [{
                    "users": ["jon@soh.re"],
                    "actions": ["read", "create", "update", "delete"]
                  }],
                  "defaultPolicy": ["read"],
                  "anonymousPolicy": ["read"]
                }
              }
            }
          }
        }
name: zot-virtualservice

externalSecret:
  enabled: true
  storeName: passbolt
  resourceId: a604544c-67bd-4080-ae39-27cbca345708
  clientId: Ov23liLygAflIzrCKJhi

sharedPvc:
  enabled: false
  name: zot-rwx
  storage: 80Gi
  storageClassName: longhorn
