zot:
  service:
    type: ClusterIP
  persistence: true
  pvc:
    create: true
  podAnnotations:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]
