apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-rpc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.passbolt.storeName }}
  target:
    name: garage-rpc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        rpcSecret: '{{ `{{ index (fromJson .bundle) "GARAGE_RPC_SECRET" }}` }}'
  data:
    - secretKey: bundle
      remoteRef:
        key: {{ .Values.passbolt.resourceId }}
        property: password
