apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-rpc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.passbolt.storeName }}
  target:
    name: garage-rpc
    creationPolicy: Owner
  data:
    - secretKey: rpcSecret
      remoteRef:
        key: {{ .Values.passbolt.resourceId }}
        property: GARAGE_RPC_SECRET

