apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: postgres-virtualservice
spec:
  hosts:
  - "postgres.soh.re"
  gateways:
  - istio-system/http-gateway
  http:
  - route:
    - destination:
        host: postgres-operator-postgres-operator-ui
        port:
          number: 80
