apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor-virtualservice
spec:
  hosts:
  - "harbor.soh.re"
  gateways:
  - istio-system/http-gateway
  http:
  - route:
    - destination:
        host: harbor.harbor.svc.cluster.local
        port:
          number: 80
