harbor:
  updateStrategy:
    type: Recreate
  externalURL: https://harbor.soh.re
  expose:
    type: clusterIP
    tls:
      enabled: false

  portal:
    revisionHistoryLimit: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]
  core:
    revisionHistoryLimit: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]

  jobservice:
    revisionHistoryLimit: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]
  registry:
    credentials:
      username: 'harbor'
      password: 'password'
      # If you update the username or password of registry, make sure use cli tool htpasswd to generate the bcrypt hash
      # e.g. "htpasswd -nbBC10 $username $password"
      htpasswd: 'harbor:$2y$10$o1jo.OXGFzLybskTVQ/xcuLs58mV6M91xsg/TZ852e7EgGS3LpuPS'
    revisionHistoryLimit: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]
  database:
    revisionHistoryLimit: 1
    internal:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/arch"
                  operator: In
                  values: ["amd64"]
  redis:
    internal:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/arch"
                  operator: In
                  values: ["amd64"]

  exporter:
    revisionHistoryLimit: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]

  nginx:
    revisionHistoryLimit: 1
    replicas: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]

