apiVersion: v2
name: istio
version: 1.27.1
dependencies:
  - name: base
    version: 1.27.1
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.27.1
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    version: 1.27.1
    repository: https://istio-release.storage.googleapis.com/charts
