apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-sso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: argocd-sso
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Release.Namespace }}-argocd-sso
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
