apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  hosts:
  - "argocd.soh.re"
  gateways:
  - istio-system/http-gateway
  http:
  - route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local  # Service name and namespace for ArgoCD
        port:
          number: 80
