apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oracle-api-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: oracle-api-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Release.Namespace }}--oracle-api-creds
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
