apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-soh-re-tls
  namespace: istio-system
spec:
  dnsNames:
  - longhorn.soh.re
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http
  secretName: longhorn-soh-re-tls
