apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-sso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: longhorn-sso
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Release.Namespace }}-longhorn-sso
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
