apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: longhorn-virtualservice
spec:
  gateways:
  - istio-system/longhorn-soh-re-gateway
  hosts:
  - longhorn.soh.re
  http:
  - match:
    - scheme:
        exact: http
      uri:
        prefix: /
    redirect:
      redirectCode: 302
      scheme: https
  - route:
    - destination:
        host: oauth2-proxy
        port:
          number: 80
