apiVersion: v2
name: hockey
description: A Helm chart for deploying hockey with a redis service
type: application
version: 0.1.0
appVersion: "v1"
dependencies:
  - name: helm-webapp
    alias: webapp
    version: 4.2.4
    repository: "oci://zot.soh.re/jmainguy"
