apiVersion: v2
name: hockey
description: A Helm chart for deploying hockey with a redis service
type: application
version: 0.1.1
appVersion: "v1.13.0"
dependencies:
  - name: helm-webapp
    alias: webapp
    version: 4.3.0
    repository: "oci://zot.soh.re/jmainguy"
