apiVersion: v2
name: garage-stack
description: Garage object storage and Valkey metadata for Zot
type: application
version: 0.1.0
appVersion: "2.3.0"
dependencies:
  - name: garage
    version: "2.3.0"
    repository: https://deimosfr.github.io/deimosfr-charts/
