passbolt:
  storeName: passbolt
  resourceId: c26921fb-ba83-4c45-a73f-b33903ece7c2

valkey:
  image: valkey/valkey:9.1-alpine@sha256:de31910896150d5e754a07d57d227cfdde4e258ddd0d1aa4607f2d2f95843715
  storageClassName: longhorn
  storage: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
